### PR TITLE
New Build System

### PR DESCRIPTION
**Pull request by SlinkyPotato**
Hiya, I was looking for a really great build template and came across this one. I thought I would add a few additions to it. I also noticed that `make spunch` wasn't really working. Here's a short list of the changes I've made, feel free to make any other changes:

* FIX: upload to FBI app, use servefile.py instead of java socket (spunch only works on FBI v1.x)
* Reorganized files and scripts to their own folders.
* Update README.md
* Add support for IntelliJ's CLion IDE.
* Add windows batch scripts for faster builds (can be set to buttons in CLion).
* Add MAJOR, MINOR, MICRO version numbers to `AppInfo` for building.
* Add romfs directory support.
* Include zipped [bannertool], [makerom], (windows) [zip], and [libbz2.dll] executables.
* Rename 3dsxlink make target to hblancher target
* Rename spunch make target to fbi target
* Add more details to README.md
* Add General Purpose Output C++ class
* Include essential annoying to find buildtools

### CODE REVIEW

**Comment by TricksterGuy** [comment]
Thanks, I have been out of the loop with the changes to libctru and other tools for the past 7 months.

Hmm I've looked at your pull requrest and while I don't agree with every change you've made in this pull request there are some great things you have done, and I have suggestions.

FIX: upload to FBI app, use servefile.py instead of java socket (spunch only works on FBI v1.x)
 - This is great.

Reorganized files and scripts to their own folders.
 - The directory structure looks the same?

Update README.md / Add more details to README.md
 - This is great, noticed my markdown was a bit off.

Add support for IntelliJ's CLion IDE.
 - I don't agree fully with this change.  This template is geared more towards Code::Blocks.  I want this template to be as uncluttered as possible.
 - You are free to fork off my template and make changes to support CLion and remove the Code::Blocks related stuff

Include zipped [bannertool], [makerom], (windows) [zip], and [libbz2.dll] executables.  / Include essential annoying to find buildtools
 - I don't agree with this change, though my opinion on this may be in the minority.
 - In my own development I copied only the binaries I needed into the devkitarm/bin directory. 
 - Looking at most of these templates...  Some templates have buildtools in an external repo.  And other just package every single binary compiled for every single os and cpu in their repos.  I think this is very wasteful and adds unnecessary clutter, and encourages people to just copy everything for every single 3ds project they are developing.
 - There is no need to have these sitting in every project folder for every 3ds homebrew you are developing if that step is done first.  Just pick the binaries you need and move them to where they can be easily accessed by all homebrew.
- Then again I kinda contradict myself by having that sockfile.jar file sitting there... Hah


Add windows batch scripts for faster builds (can be set to buttons in CLion).
 - Ehh at the need to have these.  But I am not familiar with CLion.

Add MAJOR, MINOR, MICRO version numbers to AppInfo for building.
 - Ok I see new makerom params?

Add romfs directory support.
 - Good

Rename 3dsxlink make target to hblancher target
 - Good

Rename spunch make target to fbi target
 - Good

Add General Purpose Output C++ class
 - Ehh, I don't want to include anything other than a main.cpp file that's just a hello world type thing.


Also I see your CMakeLists.txt file I dont think anything needs to be hardcoded there. A better approach would be to simply get the environment variables DEVKITPRO and DEVKITARM instead of assuming a hardcoded directory. you should just be able to say $ENV{DEVKITARM} for reference the makefile included with devkitpro are set up to fail if those two environment variables aren't set.

Though switching the 3ds makefile to Cmake would resolve the need to have separate little templates  for every single IDE out there.

Yeah be sure to add to the gbatemp wiki - https://wiki.gbatemp.net/wiki/3DS_Homebrew_Development#Editor_setup

**Comment by SlinkyPotato** [comment]
Thanks for the feedback! I've only started homebrew development in C/C++ very recently so I'm still trying to figure things out. 

The file reorganization was kinda misleading (I only moved maybe 2 files, sorry for the confusion). 

The batch files aren't really needed and I'll remove them. 

I'm not entirely sure if makerom recently added the major/minor/micro params but I noticed projects to have them in the makefile. I figured it would be good to keep track of versioning within the app similar to how `package.json` does in npm web apps. 

I agree that repos should be kept clutter free and tbh I was going back and forth on whether to include the buildtools. One thing that I found frustrating was the lack of simplicity for building on windows. I work across 3 machines and as you can tell it gets annoying having to download from various places. Ideally I wanted a build template that has minimal external dependencies and working for many years. I'm pretty anxious about links dying overtime.

IntelliJ is one of the best IDEs I've ever used and I've tried plenty. It has very powerful refactoring, code analysis, auto-completion, large market of third-party plugin support, runs quickly and looks beautiful. I was thinking that the ideal starting template would be one that supports many IDEs or conversely one that is neutral. 

Having both CMake and a makefile doesn't really make sense. I've only briefly read about what CMake can do but from my understanding it is just as you said. I'm pretty new to C/C++ development. I'll have to read more on CMake to understand how to really use it.

Let me know what you think. I'll be sure to update the wiki thx!

**Comment by TricksterGuy** [comment]
So I will reimplement most of your changes in my own way.

I just pushed a new Makefile based on current devkitPro files and did some cleaning up.  Messy...

**Comment by TricksterGuy** [comment]
(Almost 2 years later...) Blah, I should have done something about this months ago... but alas other open source projects have higher precedence.  I'm now fine with having an all in one solution supporting various IDEs and people can remove the stuff they don't want.

Well I would like CMake support as that can generate a Code::Blocks project, but the problem with that is keeping it inline with the official Makefile devkitpro supports. May just stick with the Makefile.

Let me review everything again, and review the current devkitpro Makefiles.

**Comment by TricksterGuy** [comment]
Hmm scratching my head over my disappearance past my last message... I'm assuming something came up

But after comparing this with what I have on my computer now this has become a little outdated. I think I am going to keep the template as it is now.

**Pull request closed without merging**
